# Generated by Django 5.1.6 on 2025-02-13 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booked_by', models.CharField(max_length=255)),
                ('booking_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
    ]
