# Generated by Django 5.1.6 on 2025-02-13 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 0)), name='booking_duration_positive'),
        ),
    ]
