# Generated by Django 5.1.6 on 2025-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_roombooking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_end',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
