# Generated by Django 5.1.6 on 2025-08-21 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_roombooking_booking_end'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('booking_end', models.DateTimeField(editable=False, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_start'],
            },
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'booking_start', 'booking_end'], name='bookings_bo_room_id_ed30f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 0)), name='booking_duration_positive'),
        ),
    ]
